

```{r}

if (!requireNamespace('ggpattern', quietly = TRUE)){
  install.packages('ggpattern')
}
library(ggpattern)
if (!requireNamespace('dplyr', quietly = TRUE)){
  install.packages('dplyr')
}
library(dplyr)
if (!requireNamespace('ggplot2', quietly = TRUE)){
  install.packages('ggplot2')
}
library(ggplot2)
if (!requireNamespace('ggpubr', quietly = TRUE)){
  install.packages('ggpubr')
}
library(ggpubr)
if (!requireNamespace('pwr', quietly = TRUE)){
  install.packages('pwr')
}
library(pwr)

library(tidyr)
if (!requireNamespace('tidyr', quietly = TRUE)){
  install.packages('tidyr')
}
library(tidyr)
library(ez)
# Cargamos las librerías necesarias para anova
library(dplyr)
library(ggplot2)
library(ggpubr)
library(pwr)
library(tidyr)
library(ez)
# Cargamos los datos

# Leemos los datos del CSV
datos <- read.csv2("EI-2025-1-PE1-Datos.csv")
# Mostramos los datos iniciales
head(datos)
```

#pregunta 1
```{r}
if(!require(ggpubr)) install.packages("ggpubr"); library(ggpubr)
if(!require(dplyr)) install.packages("dplyr"); library(dplyr)
if(!require(moments)) install.packages("moments"); library(moments)
if(!require(car)) install.packages("car"); library(car)
if(!require(ez)) install.packages("ez"); library(ez)
if(!require(pwr)) install.packages("pwr"); library(pwr)
if(!require(lme4)) install.packages("lme4"); library(lme4)
if(!require(emmeans)) install.packages("emmeans"); library(emmeans)
if(!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)
if(!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)

#las variables son Id, Titulo, Consola, America, Europa, Japon, Otro
#filtramos por super nintendo
datos_sp <- datos %>% filter(Consola == "Super Nintendo") %>% select(Id, Titulo, Consola, America, Europa, Japon, Otro)
#print de datos
head(datos_sp)
#para poder realizar anova tenemos que comprobar que los datos son normales y que tienen varianzas iguales
#realizamos la prueba de shapiro-wilk para comprobar la normalidad de los datos
shapiro_test <- shapiro.test(datos_sp$America)
shapiro_test
# cuento cuantos datos tenemos
nrow(datos_sp)

# Boxplot para ANOVA o Kruskal-Wallis
grafico_boxplot <- function(data, grupo, respuesta, titulo = "Boxplot de Grupos") {
  formula_str <- as.formula(paste(respuesta, "~", grupo))
  boxplot(formula_str, data = data, main = titulo, col = "lightblue", ylab = respuesta)
}
# Crear boxplot para la variable America vs Super Nintendo
grafico_boxplot(datos_sp, "Consola", "America", "Boxplot de America por Consola")
# Crear boxplot para la variable Europa vs Super Nintendo
grafico_boxplot(datos_sp, "Consola", "Europa", "Boxplot de Europa por Consola")
# Crear boxplot para la variable Japon vs Super Nintendo
grafico_boxplot(datos_sp, "Consola", "Japon", "Boxplot de Japon por Consola")
# Crear boxplot para la variable Otro vs Super Nintendo
grafico_boxplot(datos_sp, "Consola", "Otro", "Boxplot de Otro por Consola")

# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_sp$America)
qqline(datos_sp$America, col = "blue")
# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_sp$Europa)
qqline(datos_sp$Europa, col = "red")
# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_sp$Japon)
qqline(datos_sp$Japon, col = "green")
# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_sp$Otro)
qqline(datos_sp$Otro, col = "grey")


#hipotesis nula: mismo nivel de popularidad en todas las regiones
#hipotesis alternativa: diferente nivel de popularidad en todas las regiones
#realizamos la prueba de anova
anova_sp <- aov(America ~ Europa + Japon + Otro, data = datos_sp)
summary(anova_sp)

#rechaza o no la hipotesis nula
#si el p-value es menor a 0.05, se rechaza la hipotesis nula
#si el p-value es mayor a 0.05, no se rechaza la hipotesis nula
#extraemos el p-value
p_value <- summary(anova_sp)[[1]][["Pr(>F)"]][1]
p_value

# aceptamos la hipotesis nula si el p-value es mayor a 0.05
#si el p-value es menor a 0.05, se rechaza la hipotesis nula
if (p_value < 0.05) {
  print("Se rechaza la hipotesis nula")
} else {
  print("No se rechaza la hipotesis nula")
}

posthoc_tukey <- function(modelo_aov) {
  resultado <- TukeyHSD(modelo_aov)
  print(resultado)
  cat("Interpretación:\n")
  sig <- resultado[[1]][, "p adj"] < 0.05
  print(data.frame(Diferencia = rownames(resultado[[1]]), Significativa = sig))
}

posthoc_tukey(anova_sp)

comparaciones_multiples_t <- function(data, grupo, respuesta, metodo = "holm") {
  resultado <- pairwise.t.test(data[[respuesta]], data[[grupo]], p.adjust.method = metodo)
  print(resultado)
}
comparaciones_multiples_t(datos_sp, "Consola", "America", metodo = "holm")
comparaciones_multiples_t(datos_sp, "Consola", "Europa", metodo = "holm")
comparaciones_multiples_t(datos_sp, "Consola", "Japon", metodo = "holm")
comparaciones_multiples_t(datos_sp, "Consola", "Otro", metodo = "holm")



```

#pregunta 2
```{r}
#filtramos por europa gameboy
datos_g_eu <- datos %>% filter(Consola == "Gameboy") %>% select(Id, Titulo, Consola, Europa)
#filtramos por europa xbox
datos_x_eu <- datos %>% filter(Consola == "XBox") %>% select(Id, Titulo, Consola, Europa)

head(datos_g_eu)
head(datos_x_eu)

# Boxplot para ANOVA o Kruskal-Wallis
grafico_boxplot <- function(data, grupo, respuesta, titulo = "Boxplot de Grupos") {
  formula_str <- as.formula(paste(respuesta, "~", grupo))
  boxplot(formula_str, data = data, main = titulo, col = "lightblue", ylab = respuesta)
}
# Crear boxplot para la variable europa vs gameboy
grafico_boxplot(datos_g_eu, "Gameboy", "Europa", "Boxplot de Europa por Consola")
# Crear boxplot para la variable europa vs xbox
grafico_boxplot(datos_x_eu, "Xbox", "Europa", "Boxplot de Europa por Consola")

# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_g_eu$Europa)
qqline(datos_g_eu$Europa, col = "blue")
# grafico qqplot para comprobar la normalidad de los datos
qqnorm(datos_x_eu$Europa)
qqline(datos_x_eu$Europa, col = "red")

#realizamos la prueba de shapiro-wilk para comprobar la normalidad de los datos
shapiro_test_g_eu <- shapiro.test(datos_g_eu$Europa)
shapiro_test_g_eu

#realizamos la prueba de shapiro-wilk para comprobar la normalidad de los datos
shapiro_test_x_eu <- shapiro.test(datos_x_eu$Europa)
shapiro_test_x_eu

#realizamos la prueba para comparar si la popularidad de gameboy y xbox en europa con wilcoxon rank sum test
wilcox_test <- wilcox.test(datos_g_eu$Europa, datos_x_eu$Europa, paired = FALSE)
wilcox_test

# segun wilcox entonces
# si el p-value es menor a 0.05, se rechaza la hipotesis nula
# si el p-value es mayor a 0.05, no se rechaza la hipotesis nula
if (wilcox_test$p.value < 0.05) {
  print("Se rechaza la hipotesis nula")
} else {
  print("No se rechaza la hipotesis nula")
}
```

